### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (224,224) (3,224) (224,224) 

### ISSUE THREAD

**Issue by DRAhmadFaraz** [kentsommer/tensorflow-posenet#13]
![Screenshot from 2019-05-21 15-31-58](https://user-images.githubusercontent.com/38114191/58089232-b1a6d380-7bdd-11e9-87c4-0542f3cbcea7.png)
python test.py

100%|██████████| 343/343 [00:15<00:00, 22.23it/s]
  0%|          | 0/343 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 166, in <module>
    main()
  File "test.py", line 120, in main
    datasource = get_data()
  File "test.py", line 92, in get_data
    images = preprocess(images)
  File "test.py", line 58, in preprocess
    mean[0][0] += X[:,:,0]

ValueError: operands could not be broadcast together with shapes (224,224) (3,224) (224,224)

**Comment by james-yoo** [comment]
Same issue here. Does anybody know how to solved this problem?
I am using tf 3.7.2 on Window 10

**Comment by DRAhmadFaraz** [comment]
Have you tried official Caffe model Posenet instead of tensorflow.?

https://github.com/alexgkendall/caffe-posenet

**Comment by LeeC20** [comment]
Comment this line and it should work.
 # X = np.transpose(X, (2, 0, 1))

**Comment by kentsommer** [comment]
Closing this out after a long hiatus from Github. There have been a lot of updates across many of the utilized frameworks since this was published. Unfortunately I do not have the time to update it which is most likely why these issues are cropping up. 

I will happily merge in any pull requests if folks have a desire to keep this working.
